---
- name: Set the hostname for the current session
  hostname:
    name: "{{ hostname }}"

- name: Set system hostname entry in the hosts file
  lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 {{ hostname }}.localdomain {{ hostname }}"
    create: true
